name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run mock tests
      run: npm run test-controller
    - name: Start server
      run: npm start &

    - name: Wait for server to be ready
      run: sleep 5

    - name: Run external tests
      run: npm run test-external